lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, _params) do
    user_id = get_session(conn, :user_id)
    user = TaskTracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    
    resources "/users", UserController
    resources "/tasks", TaskController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do

  #   pipe_through :api
  # end
end

lib/task_tracker_web/templates/page/feed.html.eex
<h1> Your Tasks</h1>

<%= Enum.map @tasks, fn task -> %>
<%= if task.user.name == @current_user.name do %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h6 class="card-title"><%= task.user.name %></h6>
        <p>Title: <%= task.title %></p>
        <p>Description: <%= task.description %></p>
        <p>Time spent: <%= task.time %></P>
        <%= if task.completed do %>
          <p> Completed </p>
        <%= else %>
          <p> In progress</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end %> 

lib/task_tracker_web/templates/page/index.html.eex
<div class="row">
   <div class="col">

      <h1>Log In</h1>
      <%= form_tag("/session", method: :post) do %>
        <div class="form-group">
          Email
          <input type="email" name="email" placeholder="user@example.com">
          </div>
          <div class="form-group">
            <button class="btn btn-primary">Log in</button>
            <%= link "Register", to: user_path(@conn, :new) %>
          </div>
       <% end %>



   </div>
</div>